import "./globals.css";
import type { Metadata } from "next";
import { cookies } from "next/dist/client/components/headers";

export const metadata: Metadata = {
  title: "Next + Auth",
  description: "Generated by create next app",
};

type UserInfo = {
  username: string;
  email: string;
};

export default function RootLayout(props: any) {
  const cookieStore = cookies();
  const userInfoString = cookieStore.get("userInfo")?.value;
  return (
    <html lang='en'>
      <body className='flex w-full min-h-screen justify-center items-center bg-gray-50'>
        {props.children}
      </body>
    </html>
  );
}
