import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next + Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex w-full min-h-screen justify-center items-center bg-gray-50'>
        {children}
      </body>
    </html>
  );
}
